### ISSUE TITLE
error founders reward missing for block template!

### ISSUE THREAD

**Issue by bshowket** [davidTjr/Vision-Project#1]
using znomp, can you give me the sample coin config please ? getting above error and below 

> 2018-01-20 01:02:59 ERROR: ContextualCheckBlock: founders reward missing
> 2018-01-20 01:02:59 ERROR: ProcessNewBlock: AcceptBlock FAILED
> 2018-01-20 01:02:59 ERROR: ReadBlockFromDisk: OpenBlockFile failed for CBlockDiskPos(nFile=-1, nPos=0)

**Comment by sebast1an99** [comment]
^

**Comment by davidTjr** [comment]
{
"name": "Vision",
"symbol": "VIS",
"algorithm": "equihash",
"payFoundersReward": true,
"percentFoundersReward": 10,
"maxFoundersRewardBlockHeight": 849999,
"foundersRewardAddressChangeInterval": 17709.3125,
"vFoundersRewardAddress": [
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe",
"v3t9XHMCxsH21fXwf1sdZ5s6GJ1PGriR5zF",
"v3qn5TGwMCaBk3mLTeFveUog294epTAHtye",
"v3xGmaNRHmvDy5RNokpMG8GLdNU9iZFJqu8",
"v3mSKzzqvdHtpBvwUkQm1sWt7L3ENJYixhx",
"v3uYa2aVJPqJ9K3DtjboUru9MMfQk4GYNQe"
    ],
    "peerMagic": "9ef011a5"
}

**Comment by davidTjr** [comment]
#https://github.com/z-classic/z-nomp/issues/66
